### PR TITLE
Add a 'entity data api' to represent an entity's data

### PR DESCRIPTION
**Pull request by Techcable**
There are immutable and mutable versions of each entity, and factories to create both.
Plugins can also take thread-safe snapshots of entities, and copy from a data object to an entity.

I'm putting this here for your input/review, since this is a major change that has large ramifications.
We're going to have to define data for every single entity!

### CODE REVIEW

**Comment by phase** [comment]
Why is this better than storing the data inside the Entity object?

And check the Travis for your format errors.

**Comment by minecrafter** [comment]
Immutable entity data might be useful for plugins like dynmap.

**Comment by Techcable** [comment]
@phase It still stores data inside the entity object.
`public interface Entity extends MutableEntityData`
This just lets plugins access/manipulate entity data independent of an entity in the world.

**Comment by Techcable** [comment]
@minecrafter @phase Is this good to go through?

**Comment by phase** [comment]
lgtm

**Pull request merged**
