### PR TITLE
Add the plugin container

### PR DESCRIPTION
**Pull request by jamierocks**
This is required by Forge, as it has its own mod loader.

### CODE REVIEW

**Comment by PizzaCrust** [comment]
yeeeeeeeeeeeeeeeeeeeeeeees.

the plugin manager class needed this.

:+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1:

**Comment by Techcable** [comment]
👍 plugin loading should be in the implementation.

**Comment by phase** [comment]
These needs to be added into the implementation too.

**Comment by phase** [comment]
Dependencies can be removed from the pom too.

**Comment by phase** [comment]
Merged in https://github.com/FountainMC/FountainAPI/commit/738e4bd2bcb5a91fd9d87532ee8d48e43f4e3d6c

**Pull request closed without merging**
